### ISSUE TITLE
EPIC: Interface & API functions for reporting overblocking to ISPs

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/cmp-issues#132]
To provide human-powered validation of a  selection of URLs which have been blocked by ISP filters.  Reviewers should be using an unfiltered internet line (so that they can see the real destination site).

Requirements include:
- [x] Page to show list of blocked sites, with category information.  Previously reported overblocked sites are excluded from this list. Selecting an entry leads to the reporting form.  Blocked sites may initially be selected from specific categories where higher levels of overblocking are suspected.
- [x] A blocked URL entry can be dismissed if the URL points to a domain parking page, is no longer a live site, etc.  This way, low value results or false positives can be excluded from future review.
- [x] Report form. page to collect: 
- reporter information (name, email), 
- description of problem/justification for unblocking
- Checkbox list of ISPs who have blocked the site
- [x] On submission, a template email is filled out and sent to each of the blocking ISPs, Cc ORG and the reporter.  
- [x] It should be possible to go directly to the report form for a URL from a blocked.org.uk results page
- [x] Backend watches for reported sites to become unblocked, and notifies ORG and reporter

**Comment by dantheta** [comment]
All of these items have been implemented.  Testing, tweaking and improvements in progress.
