### ISSUE TITLE
EPIC: Data management pages for probe users

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#19]
As a probe user I want to manage the data held on me by the blocked.org.uk project so that I can keep it up to date or delete it.

This issue needs breaking down into finer-grained stories for implementation.

Here's a rough outline of the features we might want to build for this:
- [ ] Login page for probe users (email address and password were required on registration).
  - [ ] Log out button
  - [ ] Session time-out
- [ ] User account page, to show:
  - [ ] Email address
  - [ ] User creation date
  - [ ] Registered probes
  - [ ] Probe statistics (e.g. number of URLs tested, percentage of those that were blocked, etc)?
- [ ] Probes pages to show (for each probe registered by the logged in user)
  - [ ] Probe HMAC (we're logged in so this should be ok)
  - [ ] Date of registration
  - [ ] Date of last activity
  - [ ] URLs tested by this probe, plus results (do we show full URLs or just hashes?)
  - [ ] URLs submitted to the testing queue from this probe
- [ ] Data management features
  - [ ] Change email address
  - [ ] Change password
  - [ ] Delete probe
  - [ ] Delete all data (just the user's data or the results submitted by their probe too?)
  - [ ] Delete account

In addition to this being a useful feature for users it would help us meet our obligations under the Data Protection Act (#9)
